# Generated by Django 5.0.4 on 2024-06-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0036_foodreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodReview',
        ),
    ]
