# Generated by Django 5.0.4 on 2024-06-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0038_foodreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='user', max_length=40)),
                ('comment', models.CharField(max_length=400)),
                ('newsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newscommet', to='drf.news')),
            ],
        ),
    ]
